#這是Service3的註冊檔案
#設定Server Port為8990
server:
    port:8990

message: This is a Config-server1 yml file

#設定 Eureka 註冊的路徑    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8994/eureka/


